version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: rate_limiter_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: rate_limiter_api
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEFAULT_CAPACITY: 10
      DEFAULT_REFILL_RATE: 1.0
      FAIL_OPEN: "true"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
